version: '3.9'

services:
  database:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=trunc

volumes:
  postgres: